### ISSUE TITLE
Receiving errors

### ISSUE THREAD

**Issue by arkanmgerges** [remche/terraform-openstack-rke#64]
Hi, I'm trying to install RKE but I'm receiving some errors.

Openstack version: "Train"

**terraform.tvars:**
```
edge_count    = 1
worker_count  = 1
master_count = 1

master_labels = { "node-role.kubernetes.io/master" = "true" }
edge_labels   = { "node-role.kubernetes.io/edge" = "true" }
public_net_name = "provider"
master_flavor_name = "a.large"
worker_flavor_name = "a.large"
edge_flavor_name = "a.large"

cluster_name = "rke"
ssh_keypair_name = "local"
nodes_net_cidr = "10.13.0.0/24"
dns_servers = ["8.8.8.8"]
dns_domain = "arkan.cloud."

use_ssh_agent = false

image_name = "ubuntu-18.04-minimal-cloudimg-amd64"
user_data_file = "rancher.yml"
acme_email = "arkan.m.gerges@gmail.com"
```

**rancher.yml**

```
#cloud-config

ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYQykR9v8sGtHV0fl1Otm8N3nGFUYg8iO5IhODQO1zHtIAB8/px0JSu8g1EifbXzvx3GUUYDW2lNBbUYPOP1Os27M6lYz68qYKxMjLXraEHt9jNe7aUVIyNu2iGc3ZAgSrkRabw7P05ijLdH3A6MscQnc4tqLE92a3z/QGcANvtymJvpkvhuE3iUz92NxyR9AHaj9ejGbzJ2vu9kISVx2cUEvymW6x8zGh/agljsIXcp/KYUVr/MvpfVrdk7tUrLg3vAN5+273pWRGNTrtEdwhxBvSAYyU/p/C66G7ZHAILKj45rm0kpNqCNeQh2UiwmDbFEqQmtSZsEHKwRNCbdAx arkan@DESKTOP-8FQ42NL

packages:
    - docker.io

# create the docker group
groups:
    - docker

# Add default auto created user to docker group
system_info:
    default_user:
        groups: [docker]
```

[Debug with Errors](https://pastebin.com/AHrL7NcD)
